# Change these first
owner: christronyxyocum # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: TronFlix
    url: https://tronflix.app
  - name: Plex
    url: https://tronflix.app/plex/
    headers:
      - "token: $ORG_API_KEY"
  - name: Bitwarden
    url: https://bitwarden.tronflix.app
  - name: Gitea
    url: https://gitea.tronflix.app
  - name: Grafana
    url: https://grafana.tronflix.app
  - name: Jackett
    url: https://tronflix.app/jackett/
  - name: Library
    url: https://library.tronflix.app
  - name: NZBGet
    url: https://tronflix.app/nzbget/
    headers:
      - "token: $ORG_API_KEY"
  - name: NZBHydra
    url: https://tronflix.app/nzbhydra2/
    headers:
      - "token: $ORG_API_KEY"
  - name: Ombi
    url: https://tronflix.app/ombi/
    headers:
      - "token: $ORG_API_KEY"
  - name: PiHole
    url: https://pihole.tronflix.app
    headers:
      - "token: $ORG_API_KEY"
  - name: Radarr
    url: https://tronflix.app/radarr/
    headers:
      - "token: $ORG_API_KEY"
  - name: Radarr4K
    url: https://tronflix.app/radarr4k/
    headers:
      - "token: $ORG_API_KEY"
  - name: Sonarr
    url: https://tronflix.app/sonarr/
    headers:
      - "token: $ORG_API_KEY"
  - name: Lidarr
    url: https://tronflix.app/lidarr/
    headers:
      - "token: $ORG_API_KEY"
  - name: Tautulli
    url: https://tronflix.app/tautulli/
    headers:
      - "token: $ORG_API_KEY"
  - name: Nagios
    url: https://nagios.tronflix.app
    expectedStatusCodes:
      - 200
      - 401
  - name: TheLounge
    url: https://tronflix.app/thelounge/
    headers:
      - "token: $ORG_API_KEY"
  - name: Deluge
    url: https://tronflix.app/deluge/
    headers:
      - "token: $ORG_API_KEY"
  - name: Nextcloud
    url: https://nextcloud.tronflix.app
  - name: Chevereto
    url: https://gallery.tronflix.app
  - name: XBackBone
    url: https://sharex.tronflix.app
  - name: MediaButler
    url: https://tronflix.app/mediabutler/
  - name: Netdata
    url: https://tronflix.app/netdata/
  - name: FileBrowser
    url: https://files.tronflix.app
    headers:
      - "token: $ORG_API_KEY"
  - name: Tdarr
    url: https://tdarr.tronflix.app
    headers:
      - "token: $ORG_API_KEY"
  - name: Bazarr
    url: https://tronflix.app/bazarr/
    headers:
      - "token: $ORG_API_KEY"
assignees: # Users to assign downtime issues (optional)
  - christronyxyocum

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tronflix.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://tronflix.app/plugins/images/tabs/health.png
  name: TronFlix Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
