# Change these first
owner: tronyx # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: TronFlix
    url: https://tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/TronFlix_Icon_Transparent_BG.png
    expectedStatusCodes:
      - 200
  - name: Plex
    url: https://tronflix.app/plex/web/index.html
    icon: https://tronflix.app/plugins/images/tabs/plex.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Bitwarden
    url: https://bitwarden.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/bitwarden.png
    expectedStatusCodes:
      - 200
  - name: Gitea
    url: https://gitea.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/gitea.png
    expectedStatusCodes:
      - 200
  - name: Grafana
    url: https://grafana.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/grafana.png
    expectedStatusCodes:
      - 200
  - name: Jackett
    url: https://tronflix.app/jackett/UI/Login
    icon: https://tronflix.app/plugins/images/tabs/jackett.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Library
    url: https://library.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/library.png
    expectedStatusCodes:
      - 200
  - name: NZBGet
    url: https://tronflix.app/nzbget/
    icon: https://tronflix.app/plugins/images/tabs/nzbget.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: NZBHydra
    url: https://tronflix.app/nzbhydra2/
    icon: https://tronflix.app/plugins/images/tabs/nzbhydra.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Ombi
    url: https://tronflix.app/ombi/
    icon: https://tronflix.app/plugins/images/tabs/ombi.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: PiHole
    url: https://pihole.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/pihole.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Radarr
    url: https://tronflix.app/radarr/
    icon: https://tronflix.app/plugins/images/tabs/radarr.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Radarr4K
    url: https://tronflix.app/radarr4k/
    icon: https://tronflix.app/plugins/images/tabs/radarr4k.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Sonarr
    url: https://tronflix.app/sonarr/
    icon: https://tronflix.app/plugins/images/tabs/sonarr.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Lidarr
    url: https://tronflix.app/lidarr/
    icon: https://tronflix.app/plugins/images/tabs/lidarr.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Tautulli
    url: https://tronflix.app/tautulli/
    icon: https://tronflix.app/plugins/images/tabs/tautulli.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Nagios
    url: https://nagios.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/nagios.png
    expectedStatusCodes:
      - 200
      - 401
  - name: TheLounge
    url: https://tronflix.app/thelounge/
    icon: https://tronflix.app/plugins/images/tabs/thelounge.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Deluge
    url: https://tronflix.app/deluge/
    icon: https://tronflix.app/plugins/images/tabs/deluge.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
  - name: Nextcloud
    url: https://nextcloud.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/nextcloud.png
    expectedStatusCodes:
      - 200
  - name: Chevereto
    url: https://gallery.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/chevereto.png
    expectedStatusCodes:
      - 200
  - name: XBackBone
    url: https://sharex.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/xbackbone.png
    expectedStatusCodes:
      - 200
  - name: MediaButler
    url: https://tronflix.app/mediabutler/
    icon: https://tronflix.app/plugins/images/tabs/mediabutler.png
    expectedStatusCodes:
      - 200
  - name: Netdata
    url: https://tronflix.app/netdata/
    icon: https://tronflix.app/plugins/images/tabs/netdata.png
    expectedStatusCodes:
      - 200
  - name: FileBrowser
    url: https://files.tronflix.app
    icon: https://tronflix.app/plugins/images/tabs/filebrowser.png
    expectedStatusCodes:
      - 200
    headers:
      - "token: $ORG_API_KEY"
assignees: # Users to assign downtime issues (optional)
  - tronyx

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tronflix.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  publish: true
  logoUrl: https://tronflix.app/plugins/images/tabs/health.png
  name: TronFlix Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: TronFlix
      href: https://tronflix.app
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  links:
    - rel: stylesheet
      href: https://halianelf.github.io/css/upptime.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
